package com.sngular.api.generator.plugin.common.template;

import freemarker.cache.TemplateLoader;

import java.util.List;


public abstract class CommonTemplateLoader implements TemplateLoader {

  protected static final List<String> TEMPLATE_MODEL_FILES = List.of(CommonTemplateIndexConstants.TEMPLATE_CONTENT_SCHEMA,
    CommonTemplateIndexConstants.TEMPLATE_CONTENT_ENUM, CommonTemplateIndexConstants.TEMPLATE_CONTENT_SCHEMA_LOMBOK, CommonTemplateIndexConstants.TEMPLATE_MODEL_EXCEPTION);

  protected static final List<String> TEMPLATE_ANNOTATION_FILES = List.of(CommonTemplateIndexConstants.TEMPLATE_NOT_NULL_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_NOT_NULL_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MAX_INTEGER_ANNOTATION, CommonTemplateIndexConstants.TEMPLATE_MAX_INTEGER_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MAX_BIG_DECIMAL_ANNOTATION, CommonTemplateIndexConstants.TEMPLATE_MAX_BIG_DECIMAL_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MAX_DOUBLE_ANNOTATION, CommonTemplateIndexConstants.TEMPLATE_MAX_DOUBLE_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MAX_FLOAT_ANNOTATION, CommonTemplateIndexConstants.TEMPLATE_MAX_FLOAT_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MIN_INTEGER_ANNOTATION, CommonTemplateIndexConstants.TEMPLATE_MIN_INTEGER_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MIN_DOUBLE_ANNOTATION, CommonTemplateIndexConstants.TEMPLATE_MIN_DOUBLE_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MIN_FLOAT_ANNOTATION, CommonTemplateIndexConstants.TEMPLATE_MIN_FLOAT_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MIN_BIG_DECIMAL_ANNOTATION, CommonTemplateIndexConstants.TEMPLATE_MIN_BIG_DECIMAL_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_SIZE_ANNOTATION, CommonTemplateIndexConstants.TEMPLATE_SIZE_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_PATTERN_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_PATTERN_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MULTIPLEOF_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MULTIPLEOF_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MAX_ITEMS_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MAX_ITEMS_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MIN_ITEMS_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_MIN_ITEMS_VALIDATOR_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_UNIQUE_ITEMS_ANNOTATION,
    CommonTemplateIndexConstants.TEMPLATE_UNIQUE_ITEMS_VALIDATOR_ANNOTATION);

  protected CommonTemplateLoader() {
  }
}
