/*
 * This source code is auto-generated by the SCS Multi-API Plugin.
 */
package com.sngular.api.generator.openapi.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotNull;

public class Item {

  @JsonProperty("id")
  @NotNull
  private String id;

  @JsonProperty("name")
  @NotNull
  private String name;

  @JsonProperty("description")
  private String description;

  public Item() {
  }

  public Item(final String id, final String name) {
    this.id = id;
    this.name = name;
  }

  public Item(final String id, final String name, final String description) {
    this.id = id;
    this.name = name;
    this.description = description;
  }

  public String getId() {
    return id;
  }

  public void setId(final String id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(final String name) {
    this.name = name;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(final String description) {
    this.description = description;
  }

}
