/*
 * This source code is auto-generated by the SCS Multi-API Plugin.
 */
package com.sngular.api.generator.openapi.api;

import com.sngular.api.generator.openapi.model.Item;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;

@RequestMapping(value = "")
public interface ItemsApi {

  @GetMapping(value = "/items", produces = { "application/json" })
  ResponseEntity<List<Item>> listItems();

  @GetMapping(value = "/items/{id}", produces = { "application/json" })
  ResponseEntity<List<Item>> listItemsByCategory(@PathVariable(name = "id") final String id);

}
